# GENERATED FILE — do not edit by hand.
# Re-generate with:
#   uv run python scripts/generate_v3_endpoints.py \
#       --spec   data/tmdb_v3_openapi_patched.json \
#       --models src/tmdbx/models/v3.py \
#       --out    src/tmdbx/endpoints/v3
from __future__ import annotations

from tmdbx.endpoints._def import EndpointDef, HTTPMethod, ParamDef, ParamKind

ENDPOINTS: list[EndpointDef] = [
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/discover/movie',
        params         = [
            ParamDef(
                name        = 'certification',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'use in conjunction with `region`',
            ),
            ParamDef(
                name        = 'certification.gte',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'use in conjunction with `region`',
            ),
            ParamDef(
                name        = 'certification.lte',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'use in conjunction with `region`',
            ),
            ParamDef(
                name        = 'certification_country',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'use in conjunction with the `certification`, `certification.gte` and `certification.lte` filters',
            ),
            ParamDef(
                name        = 'include_adult',
                kind        = ParamKind.QUERY,
                python_type = 'bool',
                required    = False,
                default     = False,
            ),
            ParamDef(
                name        = 'include_video',
                kind        = ParamKind.QUERY,
                python_type = 'bool',
                required    = False,
                default     = False,
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
            ParamDef(
                name        = 'page',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
                default     = 1,
            ),
            ParamDef(
                name        = 'primary_release_year',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
            ),
            ParamDef(
                name        = 'primary_release_date.gte',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'primary_release_date.lte',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'region',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'release_date.gte',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'release_date.lte',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'sort_by',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'popularity.desc',
            ),
            ParamDef(
                name        = 'vote_average.gte',
                kind        = ParamKind.QUERY,
                python_type = 'float',
                required    = False,
            ),
            ParamDef(
                name        = 'vote_average.lte',
                kind        = ParamKind.QUERY,
                python_type = 'float',
                required    = False,
            ),
            ParamDef(
                name        = 'vote_count.gte',
                kind        = ParamKind.QUERY,
                python_type = 'float',
                required    = False,
            ),
            ParamDef(
                name        = 'vote_count.lte',
                kind        = ParamKind.QUERY,
                python_type = 'float',
                required    = False,
            ),
            ParamDef(
                name        = 'watch_region',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'use in conjunction with `with_watch_monetization_types ` or `with_watch_providers `',
            ),
            ParamDef(
                name        = 'with_cast',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'can be a comma (`AND`) or pipe (`OR`) separated query',
            ),
            ParamDef(
                name        = 'with_companies',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'can be a comma (`AND`) or pipe (`OR`) separated query',
            ),
            ParamDef(
                name        = 'with_crew',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'can be a comma (`AND`) or pipe (`OR`) separated query',
            ),
            ParamDef(
                name        = 'with_genres',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'can be a comma (`AND`) or pipe (`OR`) separated query',
            ),
            ParamDef(
                name        = 'with_keywords',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'can be a comma (`AND`) or pipe (`OR`) separated query',
            ),
            ParamDef(
                name        = 'with_origin_country',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'with_original_language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'with_people',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'can be a comma (`AND`) or pipe (`OR`) separated query',
            ),
            ParamDef(
                name        = 'with_release_type',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
                description = 'possible values are: [1, 2, 3, 4, 5, 6] can be a comma (`AND`) or pipe (`OR`) separated query, can be used in conjunctio',
            ),
            ParamDef(
                name        = 'with_runtime.gte',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
            ),
            ParamDef(
                name        = 'with_runtime.lte',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
            ),
            ParamDef(
                name        = 'with_watch_monetization_types',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'possible values are: [flatrate, free, ads, rent, buy] use in conjunction with `watch_region`, can be a comma (`AND`) or ',
            ),
            ParamDef(
                name        = 'with_watch_providers',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'use in conjunction with `watch_region`, can be a comma (`AND`) or pipe (`OR`) separated query',
            ),
            ParamDef(
                name        = 'without_companies',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'without_genres',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'without_keywords',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'without_watch_providers',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'year',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
            ),
        ],
        response_model = 'Field3DiscoverMovieGetResponse',
        description    = 'Find movies using over 30 filters and sort options.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/discover/tv',
        params         = [
            ParamDef(
                name        = 'air_date.gte',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'air_date.lte',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'first_air_date_year',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
            ),
            ParamDef(
                name        = 'first_air_date.gte',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'first_air_date.lte',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'include_adult',
                kind        = ParamKind.QUERY,
                python_type = 'bool',
                required    = False,
                default     = False,
            ),
            ParamDef(
                name        = 'include_null_first_air_dates',
                kind        = ParamKind.QUERY,
                python_type = 'bool',
                required    = False,
                default     = False,
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
            ParamDef(
                name        = 'page',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
                default     = 1,
            ),
            ParamDef(
                name        = 'screened_theatrically',
                kind        = ParamKind.QUERY,
                python_type = 'bool',
                required    = False,
            ),
            ParamDef(
                name        = 'sort_by',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'popularity.desc',
            ),
            ParamDef(
                name        = 'timezone',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'vote_average.gte',
                kind        = ParamKind.QUERY,
                python_type = 'float',
                required    = False,
            ),
            ParamDef(
                name        = 'vote_average.lte',
                kind        = ParamKind.QUERY,
                python_type = 'float',
                required    = False,
            ),
            ParamDef(
                name        = 'vote_count.gte',
                kind        = ParamKind.QUERY,
                python_type = 'float',
                required    = False,
            ),
            ParamDef(
                name        = 'vote_count.lte',
                kind        = ParamKind.QUERY,
                python_type = 'float',
                required    = False,
            ),
            ParamDef(
                name        = 'watch_region',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'use in conjunction with `with_watch_monetization_types ` or `with_watch_providers `',
            ),
            ParamDef(
                name        = 'with_companies',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'can be a comma (`AND`) or pipe (`OR`) separated query',
            ),
            ParamDef(
                name        = 'with_genres',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'can be a comma (`AND`) or pipe (`OR`) separated query',
            ),
            ParamDef(
                name        = 'with_keywords',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'can be a comma (`AND`) or pipe (`OR`) separated query',
            ),
            ParamDef(
                name        = 'with_networks',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
            ),
            ParamDef(
                name        = 'with_origin_country',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'with_original_language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'with_runtime.gte',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
            ),
            ParamDef(
                name        = 'with_runtime.lte',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
            ),
            ParamDef(
                name        = 'with_status',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'possible values are: [0, 1, 2, 3, 4, 5], can be a comma (`AND`) or pipe (`OR`) separated query',
            ),
            ParamDef(
                name        = 'with_watch_monetization_types',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'possible values are: [flatrate, free, ads, rent, buy] use in conjunction with `watch_region`, can be a comma (`AND`) or ',
            ),
            ParamDef(
                name        = 'with_watch_providers',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'use in conjunction with `watch_region`, can be a comma (`AND`) or pipe (`OR`) separated query',
            ),
            ParamDef(
                name        = 'without_companies',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'without_genres',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'without_keywords',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'without_watch_providers',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'with_type',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'possible values are: [0, 1, 2, 3, 4, 5, 6], can be a comma (`AND`) or pipe (`OR`) separated query',
            ),
        ],
        response_model = 'Field3DiscoverTvGetResponse',
        description    = 'Find TV shows using over 30 filters and sort options.',
    ),
]
