# GENERATED FILE — do not edit by hand.
# Re-generate with:
#   uv run python scripts/generate_v3_endpoints.py \
#       --spec   data/tmdb_v3_openapi_patched.json \
#       --models src/tmdbx/models/v3.py \
#       --out    src/tmdbx/endpoints/v3
from __future__ import annotations

from tmdbx.endpoints._def import EndpointDef, HTTPMethod, ParamDef, ParamKind

ENDPOINTS: list[EndpointDef] = [
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/changes',
        params         = [
            ParamDef(
                name        = 'end_date',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'page',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
                default     = 1,
            ),
            ParamDef(
                name        = 'start_date',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
        ],
        response_model = 'Field3TvChangesGetResponse',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/airing_today',
        params         = [
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
            ParamDef(
                name        = 'page',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
                default     = 1,
            ),
            ParamDef(
                name        = 'timezone',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
        ],
        response_model = 'Field3TvAiringTodayGetResponse',
        description    = 'Get a list of TV shows airing today.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/on_the_air',
        params         = [
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
            ParamDef(
                name        = 'page',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
                default     = 1,
            ),
            ParamDef(
                name        = 'timezone',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
        ],
        response_model = 'Field3TvOnTheAirGetResponse',
        description    = 'Get a list of TV shows that air in the next 7 days.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/popular',
        params         = [
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
            ParamDef(
                name        = 'page',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
                default     = 1,
            ),
        ],
        response_model = 'Field3TvPopularGetResponse',
        description    = 'Get a list of TV shows ordered by popularity.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/top_rated',
        params         = [
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
            ParamDef(
                name        = 'page',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
                default     = 1,
            ),
        ],
        response_model = 'Field3TvTopRatedGetResponse',
        description    = 'Get a list of TV shows ordered by rating.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'append_to_response',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'comma separated list of endpoints within this namespace, 20 items max',
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
        ],
        response_model = 'Field3TvSeriesIdGetResponse',
        description    = 'Get the details of a TV show.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/account_states',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'session_id',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'guest_session_id',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
        ],
        response_model = 'Field3TvSeriesIdAccountStatesGetResponse',
        description    = 'Get the rating, watchlist and favourite status.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/aggregate_credits',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
        ],
        response_model = 'Field3TvSeriesIdAggregateCreditsGetResponse',
        description    = 'Get the aggregate credits (cast and crew) that have been added to a TV show.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/alternative_titles',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdAlternativeTitlesGetResponse',
        description    = 'Get the alternative titles that have been added to a TV show.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/changes',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'end_date',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'page',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
                default     = 1,
            ),
            ParamDef(
                name        = 'start_date',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
        ],
        response_model = 'Field3TvSeriesIdChangesGetResponse',
        description    = 'Get the recent changes for a TV show.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/content_ratings',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdContentRatingsGetResponse',
        description    = 'Get the content ratings that have been added to a TV show.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/credits',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
        ],
        response_model = 'Field3TvSeriesIdCreditsGetResponse',
        description    = 'Get the latest season credits of a TV show.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/episode_groups',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdEpisodeGroupsGetResponse',
        description    = 'Get the episode groups that have been added to a TV show.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/external_ids',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdExternalIdsGetResponse',
        description    = 'Get a list of external IDs that have been added to a TV show.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/images',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'include_image_language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'specify a comma separated list of ISO-639-1 values to query, for example: `en-US,null`',
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
        ],
        response_model = 'Field3TvSeriesIdImagesGetResponse',
        description    = 'Get the images that belong to a TV series.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/keywords',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdKeywordsGetResponse',
        description    = 'Get a list of keywords that have been added to a TV show.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/latest',
        params         = [],
        response_model = 'Field3TvLatestGetResponse',
        description    = 'Get the newest TV show ID.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/lists',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
            ParamDef(
                name        = 'page',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
                default     = 1,
            ),
        ],
        response_model = 'Field3TvSeriesIdListsGetResponse',
        description    = 'Get the lists that a TV series has been added to.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/recommendations',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
            ParamDef(
                name        = 'page',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
                default     = 1,
            ),
        ],
        response_model = 'Field3TvSeriesIdRecommendationsGetResponse',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/reviews',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
            ParamDef(
                name        = 'page',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
                default     = 1,
            ),
        ],
        response_model = 'Field3TvSeriesIdReviewsGetResponse',
        description    = 'Get the reviews that have been added to a TV show.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/screened_theatrically',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdScreenedTheatricallyGetResponse',
        description    = 'Get the seasons and episodes that have screened theatrically.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/similar',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'str',
                required    = True,
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
            ParamDef(
                name        = 'page',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
                default     = 1,
            ),
        ],
        response_model = 'Field3TvSeriesIdSimilarGetResponse',
        description    = 'Get the similar TV shows.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/translations',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdTranslationsGetResponse',
        description    = 'Get the translations that have been added to a TV show.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/videos',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'include_video_language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'filter the list results by language, supports more than one value by using a comma',
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
        ],
        response_model = 'Field3TvSeriesIdVideosGetResponse',
        description    = 'Get the videos that belong to a TV show.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/watch/providers',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdWatchProvidersGetResponse',
        description    = 'Get the list of streaming providers we have for a TV show.',
    ),
    EndpointDef(
        method         = HTTPMethod.POST,
        path_template  = '/3/tv/{series_id}/rating',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'guest_session_id',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'session_id',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'Content-Type',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = True,
                default     = 'application/json;charset=utf-8',
            ),
        ],
        response_model = 'Field3TvSeriesIdRatingPostResponse',
        request_model  = 'Field3TvSeriesIdRatingPostRequest',
        description    = 'Rate a TV show and save it to your rated list.',
    ),
    EndpointDef(
        method         = HTTPMethod.DELETE,
        path_template  = '/3/tv/{series_id}/rating',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'Content-Type',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'application/json;charset=utf-8',
            ),
            ParamDef(
                name        = 'guest_session_id',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'session_id',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
        ],
        response_model = 'Field3TvSeriesIdRatingDeleteResponse',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/season/{season_number}',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'append_to_response',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'comma separated list of endpoints within this namespace, 20 items max',
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberGetResponse',
        description    = 'Query the details of a TV season.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/season/{season_number}/account_states',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'session_id',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'guest_session_id',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberAccountStatesGetResponse',
        description    = 'Get the rating, watchlist and favourite status.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/season/{season_number}/aggregate_credits',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberAggregateCreditsGetResponse',
        description    = 'Get the aggregate credits (cast and crew) that have been added to a TV season.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/season/{season_id}/changes',
        params         = [
            ParamDef(
                name        = 'end_date',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'page',
                kind        = ParamKind.QUERY,
                python_type = 'int',
                required    = False,
                default     = 1,
            ),
            ParamDef(
                name        = 'start_date',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'season_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeasonSeasonIdChangesGetResponse',
        description    = 'Get the recent changes for a TV season.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/season/{season_number}/credits',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberCreditsGetResponse',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/season/{season_number}/external_ids',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberExternalIdsGetResponse',
        description    = 'Get a list of external IDs that have been added to a TV season.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/season/{season_number}/images',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'include_image_language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'specify a comma separated list of ISO-639-1 values to query, for example: `en-US,null`',
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberImagesGetResponse',
        description    = 'Get the images that belong to a TV season.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/season/{season_number}/translations',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberTranslationsGetResponse',
        description    = 'Get the translations for a TV season.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/season/{season_number}/videos',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'include_video_language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'filter the list results by language, supports more than one value by using a comma',
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberVideosGetResponse',
        description    = 'Get the videos that belong to a TV season.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/season/{season_number}/watch/providers',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberWatchProvidersGetResponse',
        description    = 'Get the list of streaming providers we have for a TV season.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'episode_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'append_to_response',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'comma separated list of endpoints within this namespace, 20 items max',
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberEpisodeEpisodeNumberGetResponse',
        description    = 'Query the details of a TV episode.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/account_states',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'session_id',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'episode_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'guest_session_id',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberEpisodeEpisodeNumberAccountStatesGetResponse',
        description    = 'Get the rating, watchlist and favourite status.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/episode/{episode_id}/changes',
        params         = [
            ParamDef(
                name        = 'episode_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvEpisodeEpisodeIdChangesGetResponse',
        description    = 'Get the recent changes for a TV episode.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/credits',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
            ParamDef(
                name        = 'episode_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberEpisodeEpisodeNumberCreditsGetResponse',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/external_ids',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'episode_number',
                kind        = ParamKind.PATH,
                python_type = 'str',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberEpisodeEpisodeNumberExternalIdsGetResponse',
        description    = 'Get a list of external IDs that have been added to a TV episode.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/images',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'include_image_language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'specify a comma separated list of ISO-639-1 values to query, for example: `en-US,null`',
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'episode_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberEpisodeEpisodeNumberImagesGetResponse',
        description    = 'Get the images that belong to a TV episode.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/translations',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'episode_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberEpisodeEpisodeNumberTranslationsGetResponse',
        description    = 'Get the translations that have been added to a TV episode.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/videos',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'include_video_language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                description = 'filter the list results by language, supports more than one value by using a comma',
            ),
            ParamDef(
                name        = 'language',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'en-US',
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'episode_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberEpisodeEpisodeNumberVideosGetResponse',
        description    = 'Get the videos that belong to a TV episode.',
    ),
    EndpointDef(
        method         = HTTPMethod.POST,
        path_template  = '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/rating',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'guest_session_id',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'session_id',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'Content-Type',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = True,
                default     = 'application/json;charset=utf-8',
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'episode_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberEpisodeEpisodeNumberRatingPostResponse',
        request_model  = 'Field3TvSeriesIdSeasonSeasonNumberEpisodeEpisodeNumberRatingPostRequest',
        description    = 'Rate a TV episode and save it to your rated list.',
    ),
    EndpointDef(
        method         = HTTPMethod.DELETE,
        path_template  = '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/rating',
        params         = [
            ParamDef(
                name        = 'series_id',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'Content-Type',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
                default     = 'application/json;charset=utf-8',
            ),
            ParamDef(
                name        = 'guest_session_id',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'session_id',
                kind        = ParamKind.QUERY,
                python_type = 'str',
                required    = False,
            ),
            ParamDef(
                name        = 'season_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
            ParamDef(
                name        = 'episode_number',
                kind        = ParamKind.PATH,
                python_type = 'int',
                required    = True,
            ),
        ],
        response_model = 'Field3TvSeriesIdSeasonSeasonNumberEpisodeEpisodeNumberRatingDeleteResponse',
        description    = 'Delete your rating on a TV episode.',
    ),
    EndpointDef(
        method         = HTTPMethod.GET,
        path_template  = '/3/tv/episode_group/{tv_episode_group_id}',
        params         = [
            ParamDef(
                name        = 'tv_episode_group_id',
                kind        = ParamKind.PATH,
                python_type = 'str',
                required    = True,
            ),
        ],
        response_model = 'Field3TvEpisodeGroupTvEpisodeGroupIdGetResponse',
        description    = 'Get the details of a TV episode group.',
    ),
]
